# Generated by Django 4.2.9 on 2024-02-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_is_active', 'Can set active user')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
