# Generated by Django 4.2.9 on 2024-01-29 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='mailing date')),
                ('mailing_time', models.TimeField(verbose_name='mailing time')),
                ('frequency', models.CharField(choices=[('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly')], max_length=50, verbose_name='frequency')),
                ('mailing_status', models.CharField(choices=[('CREATED', 'created'), ('STARTED', 'started'), ('FINISHED', 'finished')], max_length=50, verbose_name='mailing status')),
                ('is_active', models.BooleanField(default=True, verbose_name='mailing status')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailing',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='time of attempt')),
                ('status', models.CharField(choices=[('SENT', 'sent'), ('FAILED', 'failed'), ('PENDING', 'pending')], max_length=50, verbose_name='status of attempt')),
                ('server_response', models.TextField(max_length=200, verbose_name='server response')),
            ],
            options={
                'verbose_name': 'Mailing log',
                'verbose_name_plural': 'Mailing logs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Email subject')),
                ('body', models.TextField(verbose_name="Message's text")),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
